# FreeRTOS {
#   Demo{
#     ARM7_MC13224V_GCC {
#       "main.c".shape: page
#     }
#     ARM7_MC13224V_GCC.shape: package
#   }
#   Source {
#     portable {
#       GCC {
#         ARM7_MC13224V {
#           "port.c".shape: page
#           "portmacro.c".shape: page
#           "portISR.c".shape: page
#           bsp/.shape: package 
#         }
#         ARM7_MC13224V.shape: package
#       }
#       GCC.shape: package
#     }
#     portable.shape: package
#   }
# Demo.shape: package
# Source.shape: package
# }
# FreeRTOS.shape: package 

FreeRTOS/ -> Demo/
Demo/ -> ARM7_MC13224V_GCC/
ARM7_MC13224V_GCC/ {
  "main.c".shape: page
}

FreeRTOS/ -> Source/
Source/ -> portable/
portable/ -> GCC/
GCC/ -> ARM7_MC13224V/
ARM7_MC13224V/ {
  "port.c".shape: page
  "portmacro.c".shape: page
  "portISR.c".shape: page
  bsp/.shape: package
}

FreeRTOS/ <- Github.FreeRTOS/FreeRTOS
Github.FreeRTOS/FreeRTOS {
    link: https://github.com/FreeRTOS/FreeRTOS
    shape: cloud
}

Source/.shape: package
Source/ <- Github.FreeRTOS/FreeRTOS-Kernel
Github.FreeRTOS/FreeRTOS-Kernel {
    link: https://github.com/FreeRTOS/FreeRTOS-Kernel
    shape: cloud
}

# Github.shape: cloud
# Github.FreeRTOS/FreeRTOS -> Github.FreeRTOS/FreeRTOS-Kernel 

FreeRTOS/.shape: package
Demo/.shape: package
ARM7_MC13224V_GCC/.shape: package
portable/.shape: package
GCC/.shape: package
ARM7_MC13224V/.shape: package
